version: "3"
services:

  app:
    image: nextcloud:fpm
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    volumes:
      - ./data/app:/var/www/html
    depends_on:
      - database
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  http:
    image: nginx
    container_name: ${APP_NAME}_http
    restart: unless-stopped
    ports:
      - 127.0.0.1:${APP_PORT}:80
    depends_on:
      - app
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

  database:
    image: mariadb
    container_name: ${APP_NAME}_database
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
