version: "3"
services:

  app:
    image: nextcloud
    container_name: ${APP_NAME}_http
    restart: unless-stopped
    volumes:
      - ./data/app:/var/www/html
    ports:
      - 127.0.0.1:${APP_PORT}:80
    depends_on:
      - database
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  database:
    image: mariadb
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
